import { HttpInterceptorFn } from '@angular/common/http';

const REQUEST_ID_HEADER = 'X-Request-Id';

/**
 * PRD §14 Observability: "every request carries X-Request-Id (generated by the SPA if
 * absent)". Attaches a fresh id to every outgoing HTTP request so it can be correlated
 * through the backend's logs (`RequestIdFilter`, §15.6's masked logging pattern) and back
 * in the response header.
 */
export const requestIdInterceptor: HttpInterceptorFn = (req, next) => {
  const cloned = req.clone({
    setHeaders: { [REQUEST_ID_HEADER]: crypto.randomUUID() },
  });
  return next(cloned);
};
