package com.clinic.booking.config;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.MDC;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.UUID;

/**
 * PRD §14 Observability: every request carries {@code X-Request-Id} — generated by the
 * SPA if absent, echoed back on the response, and made available to every log line for
 * this request via SLF4J's {@link MDC} (consumed by {@code %X{requestId}} in the logging
 * pattern, §15.6/{@code logback-spring.xml}). Runs before every other filter (including
 * {@link RateLimitingFilter}) so the id is present for logging emitted anywhere downstream,
 * including a rate-limit rejection.
 *
 * <p><b>Known PRD conflict — not propagated into {@code appointment_audit_log}.</b> §14's
 * Observability row also says the request id is propagated "to {@code appointment_audit_log}
 * where relevant," but §7.9 defines that table's columns exhaustively ({@code id},
 * {@code appointment_id}, {@code previous_status}, {@code new_status}, {@code changed_by},
 * {@code reason}, {@code changed_at}) with no request-id column, and §17 rule 2 forbids
 * introducing a field not listed in §7. Adding one would require a schema migration, which
 * is out of scope here (no migration is being added as part of this fix). This is a
 * documented gap between §14 and §7.9/§17 rule 2, not an implementation oversight — per
 * §17 rule 2 itself ("stop and flag the gap rather than inventing a resolution"), resolving
 * it is a product/architecture decision (approve a migration adding a
 * {@code request_id} column, or amend §14 to drop this clause), not something to resolve
 * unilaterally in code.
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class RequestIdFilter extends OncePerRequestFilter {

    public static final String REQUEST_ID_HEADER = "X-Request-Id";
    public static final String MDC_KEY = "requestId";

    @Override
    protected void doFilterInternal(
            HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {
        String requestId = request.getHeader(REQUEST_ID_HEADER);
        if (!StringUtils.hasText(requestId)) {
            requestId = UUID.randomUUID().toString();
        }
        response.setHeader(REQUEST_ID_HEADER, requestId);
        MDC.put(MDC_KEY, requestId);
        try {
            filterChain.doFilter(request, response);
        } finally {
            MDC.remove(MDC_KEY);
        }
    }
}
